name: Main CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:

  deploy-dev:
    name: Deploy Dev
    uses: anilkumar-repo/enterprise-ci-cd-workflows/.github/workflows/deploy.yml@main
    with:
      deploy_provider: netlify
      environment: dev
      publish_dir: .
    secrets:
      NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      NETLIFY_SITE_ID: ${{ secrets.NETLIFY_DEV_SITE_ID }}

  validate-dev:
    name: Validate Dev
    needs: deploy-dev
    uses: anilkumar-repo/enterprise-ci-cd-workflows/.github/workflows/validate.yml@main

  rollback-dev:
    name: Rollback Dev
    if: ${{ always() && needs.validate-dev.result == 'failure' }}
    needs: validate-dev
    uses: anilkumar-repo/enterprise-ci-cd-workflows/.github/workflows/rollback.yml@main
    with:
      deploy_provider: netlify
      environment: dev