name: Higher Environment Release Pipeline

on:
  push:
    tags:
      - 'v*.*.*'

jobs:

  deploy-prod:
    name: Deploy to Production
    uses: anilkumar-repo/enterprise-ci-cd-workflows/.github/workflows/deploy-prod.yml@main

  rollback-prod:
    name: Rollback Production
    if: failure()
    needs: deploy-prod
    uses: anilkumar-repo/enterprise-ci-cd-workflows/.github/workflows/rollback-prod.yml@main